[project]
name = "port-scanner"
version = "0.1.1"
authors = [{ name="batubyte" }]

description = "Async port scanner with Nmap"
readme = "README.md"
requires-python = ">=3.13"

dependencies = []

license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Github = "https://github.com/batubyte/port-scanner"
Discord = "https://discord.gg/6H6T8aNbC6"
